version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972
      - 52783:52773
      - 53773
    volumes:
      - ./:/irisrun/repo
    environment:
      - REGISTRY=https://test.pm.community.intersystems.com/registry/
      - REGISTRYUSER=test
      - REGISTRYPASS=PassWord42